[[redirects]]
from = "/*"
to = "/index.html"
status = 200
[[plugins]]
package = "netlify-plugin-submit-sitemap"
[plugins.inputs]
baseUrl = "https://master-gaming.netlify.app"
sitemapPath = "/sitemap.xml" 
providers = ["google", "yandex"] 